// react-vue-example/auth/src/bootstrap.js
import React from "react";
import ReactDom from "react-dom";
import { createMemoryHistory, createBrowserHistory } from "history";
import App from "./App";

// Mount function to start up the App
const mount = (element, { defaultHistory, onNavigate }) => {
  const history = defaultHistory || createMemoryHistory();
  if (onNavigate) history.listen(onNavigate);
  ReactDom.render(<App history={history} />, element);

  return {
    onParentNavigate({ pathname: nextPathname }) {
      const { pathname } = history.location;
      if (pathname !== nextPathname) history.push(nextPathname);
    },
  };
};

// Run in development mode and in isolation
if (process.env.NODE_ENV === "development") {
  const element = document.getElementById("auth-dev-root");
  if (element) mount(element, { defaultHistory: createBrowserHistory() });
}

// Running through container and Exporting mount function
export default mount;

// react-vue-example/dashboard/src/bootstrap.js
import { createApp } from "vue";
import Dashboard from "./components/Dashboard.vue";

// Mount function to start up the app
const mount = (element) => {
  const app = createApp(Dashboard);
  app.mount(element);
};

// If we are in development and in isolation,
// call mount immediately
if (process.env.NODE_ENV === "development") {
  const element = document.getElementById("dashboard-dev-root");

  if (element) mount(element);
}

// We are running through container
// and we should export the mount function
export default mount;
